name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: 3.131.4.23
        username: ubuntu
        key: ${{ secrets.sshkey }}
        port: 22
        script: |
          cd /var/www/price-predictor-wwi19dsa 
          sudo git stash
          sudo git checkout master 
          sudo git stash
          sudo git pull 
          cd frontend
          ng build --prod --build-optimizer
